In [1]:
import numpy as np

**1. Установить, какие произведения матриц 𝐴𝐵 и 𝐵𝐴 определены, и найти размерности полученных матриц:**

а) A — матрица 4×2, B — матрица 4×2; **АВ и ВА не определены**

б) A — матрица 2×5, B — матрица 5×3; **АВ не определена, ВА определена 5х5**

в) A — матрица 8×3, B — матрица 3×8; **АВ определена 8х8, ВА определена 3х3**

г) A — матрица 4×4, B — матрица 4×4; **АВ и ВА определена 4х4**

**__2.__ Найти сумму и произведение матриц** $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [21]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A, B

(array([[ 1, -2],
        [ 3,  0]]),
 array([[ 4, -1],
        [ 0,  5]]))

In [25]:
print(f'Сумма матриц А и В \n{A + B}')
print(f'Произведение матриц А и В \n{A @ B}')
print(f'Произведение матриц B и A \n{B @ A}')

Сумма матриц А и В 
[[ 5 -3]
 [ 3  5]]
Произведение матриц А и В 
[[  4 -11]
 [ 12  -3]]
Произведение матриц B и A 
[[ 1 -8]
 [15  0]]


__3.__ **Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц** $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [26]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

3 * A - 2 * B + 4 * C 

array([[ 11,  -5],
       [  9, -12]])

__4.__ **Дана матрица** $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [28]:
A = np.array([[4, 1], [5, -2], [2, 3]])
AT = A.T
A, AT

(array([[ 4,  1],
        [ 5, -2],
        [ 2,  3]]),
 array([[ 4,  5,  2],
        [ 1, -2,  3]]))

In [29]:
print(f'Произведение матриц А и AT \n{A @ AT}')
print(f'Произведение матриц АT и A \n{AT @ A}')

Произведение матриц А и AT 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение матриц АT и A 
[[45  0]
 [ 0 14]]


__5*.__ **Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**